HAI GOT
BOTH SAEM 12 AN "WIN"
DIFFRINT WIN AN FAIL
BOTH OF "me" AN "you"
EITHER OF 1 AN 0
BIGGR OF 12 AN 11.999
I HAS A zmienna ITZ "you"
SMALLR OF zmienna AN "zmienna"
SUM OF 12 AN 12
DIFF OF "string" AN WIN
PRODUKT OF 134 AN FAIL
QUOSHUNT OF SUM OF 12 AN 15 AN "text"
MOD OF 100 AN 10
KTHXBYE
